// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace WebApplicationTest.DAL
{
    public partial class TestDbContext : DbContext
    {
        public virtual DbSet<Xzqh> Xzqhs { get; set; }
        public virtual DbSet<Xzqh2> Xzqh2 { get; set; }

        public TestDbContext(DbContextOptions<TestDbContext> options) 
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasPostgresExtension("adminpack");

            modelBuilder.Entity<Xzqh>(entity =>
            {
                entity.HasNoKey();
            });

            modelBuilder.Entity<Xzqh2>(entity =>
            {
                entity.HasNoKey();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}