// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplicationTest.DAL
{
    [Table("XZQH_2")]
    public partial class Xzqh2
    {
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
    }
}