// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplicationTest.DAL
{
    [Table("XZQH")]
    public partial class Xzqh
    {
        [Column("XZQDM")]
        public string Xzqdm { get; set; }
        [Column("XZQMC")]
        public string Xzqmc { get; set; }
        [Column("rowxy")]
        public string Rowxy { get; set; }
    }
}